#!/bin/bash 

if [ $# -eq 1 ]; then
  ant clean && rm -f *.jar && ant && ./$1/setup
elif [ $# -eq 2 ] && [ $2 == "all" ]; then
  dmck_dir=`pwd`
  cd ./$1 && . ./readconfig
  cd $target_sys_dir && ./compile.sh
  cd $dmck_dir && ant clean && rm -f *.jar && ant && ./$1/setup
else
  help="usage: ./compile [choose one : scm / sample-le / cassandra-2.0.0 / kudu-0.9.1 /\
  zookeeper-3.1.0] [additional option: all]"
  echo $help
fi
