#!/bin/bash

if [ $# -ne 1 ]; then
  echo "usage: resettest <testId>"
  exit 1
fi

. ./readconfig

testId=$1

mkdir $working_dir/console/$testId

rm -rf $working_dir/data/zk*/version-2
rm -rf $working_dir/log/zk*/version-2


